export const GET_DJANGOREACT = 'GET_DJANGOREACT';
export const DELETE_DJANGOREACT = 'DELETE_DJANGOREACT';
export const ADD_DJANGOREACT = 'ADD_DJANGOREACT';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';